sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_subcontractor:
    resource: |
        alias: app.unit_of_measurement
        except: ['show']
        templates: SyliusAdminBundle:Crud
        grid: app_admin_unit_of_measurement
        section: admin
    type: sylius.resource
    prefix: /admin
